// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using S3Storage.Model;
using S3Storage.Service;
using S3Storage.AWSException;
using System.Threading.Tasks;
using S3Storage.S3;
using S3Storage.Response;
using System.Collections.Generic;

namespace S3StorageSample.iOS
{
	public partial class BucketViewController : UITableViewController
	{
		DataSource dataSource;

		public BucketViewController (IntPtr handle) : base (handle)
		{
		}

		async void AddNewItem (object sender, EventArgs args)
		{

			try {
			
				string fileName = new Random ().Next (2).ToString () + ".jpg";
				byte[] buffer = File.ReadAllBytes (fileName);

				string saveAs = DateTime.UtcNow.Ticks.ToString () + "-" + fileName;
				await ServiceContainer.Resolve<S3ClientCore> ().PutObject (Title, saveAs, buffer);

				dataSource.Objects.Insert (0, new Contents () {
					Key = saveAs
				});
				using (var indexPath = NSIndexPath.FromRowSection (0, 0))
					TableView.InsertRows (new NSIndexPath[] { indexPath }, UITableViewRowAnimation.Automatic);
					
			} catch (AWSErrorException e) {
				UIAlertView alert = new UIAlertView ("Error", e.ToString (), null, "OK", null);
				alert.Show ();
			}
		}



		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Perform any additional setup after loading the view, typically from a nib.
			//NavigationItem.LeftBarButtonItem = EditButtonItem;

			var addButton = new UIBarButtonItem (UIBarButtonSystemItem.Add, AddNewItem);
			NavigationItem.RightBarButtonItem = addButton;

			TableView.Source = dataSource = new DataSource (this);

			RefreshControl = new UIRefreshControl ();
			RefreshControl.ValueChanged += async (object sender, EventArgs e) => {
				RefreshControl.BeginRefreshing ();
				await dataSource.RefreshData ();
				RefreshControl.EndRefreshing ();
				TableView.ReloadData ();
			};

		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			if (segue.Identifier == "objectSeque") {
				var indexPath = TableView.IndexPathForSelectedRow;
				var item = dataSource.Objects [indexPath.Row];

				((DetailViewController)segue.DestinationViewController).BucketName = Title;
				((DetailViewController)segue.DestinationViewController).Contents = item;
			}
		}

		class DataSource : UITableViewSource
		{
			static readonly NSString CellIdentifier = new NSString ("Cell");
			List<Contents> objects = new List<Contents> ();

			readonly BucketViewController Controller;

			public DataSource (BucketViewController controller)
			{
				this.Controller = controller;
				Initialize ();
			}

			private async void Initialize ()
			{
				await RefreshData ();
			}

			public async Task RefreshData ()
			{
				try {
					ListBucketResult result = await ServiceContainer.Resolve<S3ClientCore> ().GetBucket (Controller.Title);
					if (result.Contents != null) {
						this.Objects = new List<Contents> (result.Contents);
					} else {
						this.Objects = new List<Contents> ();
					}
				} catch (AWSErrorException e) {
					UIAlertView alert = new UIAlertView ("Error", e.ToString (), null, "OK", null);
					alert.Show ();
				}
			}

			public IList<Contents> Objects {
				get { return objects; }
				set { objects = (List<Contents>)value; }
			}

			// Customize the number of sections in the table view.
			public override int NumberOfSections (UITableView tableView)
			{
				return 1;
			}

			public override int RowsInSection (UITableView tableview, int section)
			{
				return objects.Count;
			}

			// Customize the appearance of table view cells.
			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				var cell = (UITableViewCell)tableView.DequeueReusableCell (CellIdentifier, indexPath);

				cell.TextLabel.Text = objects [indexPath.Row].Key;

				return cell;
			}

			public override bool CanEditRow (UITableView tableView, NSIndexPath indexPath)
			{
				// Return false if you do not want the specified item to be editable.
				return true;
			}

			public async override void CommitEditingStyle (UITableView tableView, UITableViewCellEditingStyle editingStyle, NSIndexPath indexPath)
			{
				if (editingStyle == UITableViewCellEditingStyle.Delete) {
					// Delete the row from the data source.
					try {
						await ServiceContainer.Resolve<S3ClientCore> ().DeleteObject (Controller.Title, objects [indexPath.Row].Key);
						objects.RemoveAt (indexPath.Row);
						Controller.TableView.DeleteRows (new NSIndexPath[] { indexPath }, UITableViewRowAnimation.Fade);
					} catch (AWSErrorException e) {
						UIAlertView alert = new UIAlertView ("Error", e.ToString (), null, "OK", null);
						alert.Show ();
					}
				} else if (editingStyle == UITableViewCellEditingStyle.Insert) {
					// Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view.
				}
			}

			/*
			// Override to support rearranging the table view.
			public override void MoveRow (UITableView tableView, NSIndexPath sourceIndexPath, NSIndexPath destinationIndexPath)
			{
			}
			*/

			/*
			// Override to support conditional rearranging of the table view.
			public override bool CanMoveRow (UITableView tableView, NSIndexPath indexPath)
			{
				// Return false if you do not want the item to be re-orderable.
				return true;
			}
			*/
		}
	}
}
